### ISSUE TITLE
installation link is dead. (Maybe typo)

### ISSUE THREAD

**Issue by crcrpar** [pytorch/cppdocs#1]
Hi,

In index.html (https://pytorch.org/cppdocs/frontend.html#installation), I couldn't jump to installation page and found that link is https://pytorch.org/cppdocs/installation.html not https://pytorch.org/cppdocs/installing.html.

**Comment by goldsborough** [comment]
Hey, thanks for catching this. We're currently fixing our download links. Please see this temporary markdown file I created with the correct download URLs: https://gist.github.com/goldsborough/fc3d94917f0405a9da7ec2899710eb9f.

 I'll update the website ASAP.

**Comment by crcrpar** [comment]
I got it. Thanks!

**Comment by perone** [comment]
Is there any particular reason for the `torch.h` be inside the `include/torch/csrc` instead of inside of `include/torch`? The `TorchConfig.cmake` isn't adding the `csrc` into the include paths, only the `torch` directory. Thanks !

**Comment by goldsborough** [comment]
@perone do you have a recent download of libtorch? There's been some recent changes, but if you download a new libtorch distribution the TorchConfig.cmake should have these lines:
```
# Include directories.
if (EXISTS "${TORCH_INSTALL_PREFIX}/lib/include")
  set(TORCH_INCLUDE_DIRS
    ${TORCH_INSTALL_PREFIX}/lib/include
    ${TORCH_INSTALL_PREFIX}/lib/include/torch/csrc/api/include)
else()
  set(TORCH_INCLUDE_DIRS
    ${TORCH_INSTALL_PREFIX}/include
    ${TORCH_INSTALL_PREFIX}/include/torch/csrc/api/include)
endif()
```

which configures the correct include paths. There should also only be one `torch.h`, which is `libtorch/include/torch/csrc/api/include/torch/torch.h`. The one in `torch/csrc/` was recently deleted.

Please let me know if this is not the case and we'll fix it.

**Comment by perone** [comment]
Thanks for the reply, I guess I have an old version then (I don't have this directory structure, and there is no `torch.h` inside the `api/include/torch`), I got it from this link (from the gist): https://download.pytorch.org/libtorch/nightly/cpu/libtorch-macos-latest.zip, is there any other place where I can find the recent binaries ?

**Comment by goldsborough** [comment]
No that's the correct link. There's something funny going on, the MacOS distribution seems to be out of date. The linux distribution is updated. I will have to talk to our release folks about this. That will likely have to wait until tomorrow though. I'll get back to you here as soon as I can. Maybe you can try out the linux distro in a docker image in the meantime.

**Comment by perone** [comment]
Oka, no problem, I can wait for it. Thanks a lot for the quick replies !

**Comment by goldsborough** [comment]
The mac build is now fixed. You can also use our website now to get the latest links: https://pytorch.org/get-started/locally/
Click on "LibTorch" and then "Mac" and "CPU"  and it should show a nice link:
<img width="753" alt="screen shot 2018-10-01 at 14 45 59" src="https://user-images.githubusercontent.com/6429851/46317705-bbb18e80-c588-11e8-9e8b-b4a21273c5e7.png">

**Comment by perone** [comment]
That's amazing, thanks a lot @goldsborough !
